package vn.com.nhatro.model;
// default package
// Generated Sep 9, 2014 4:09:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "nhatro")
public class Comment implements java.io.Serializable {

	private Integer commentid;
	private Nhatro nhatro;
	private User user;
	private String comment;
	private Date datecomment;

	public Comment() {
	}

	public Comment(Nhatro nhatro, User user, String comment, Date datecomment) {
		this.nhatro = nhatro;
		this.user = user;
		this.comment = comment;
		this.datecomment = datecomment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "COMMENTID", unique = true, nullable = false)
	public Integer getCommentid() {
		return this.commentid;
	}

	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NHATROID", nullable = false)
	public Nhatro getNhatro() {
		return this.nhatro;
	}

	public void setNhatro(Nhatro nhatro) {
		this.nhatro = nhatro;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USERNAME", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "COMMENT", nullable = false, length = 200)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATECOMMENT", length = 19)
	public Date getDatecomment() {
		return this.datecomment;
	}

	public void setDatecomment(Date datecomment) {
		this.datecomment = datecomment;
	}

}
