package vn.com.nhatro.model;

// default package
// Generated Aug 30, 2014 10:27:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Duong generated by hbm2java
 */
@Entity
@Table(name = "duong", catalog = "nhatro")
public class Duong implements java.io.Serializable {

	private Integer duongid;
	private String tenduong;
	private Set<Diachi> diachis = new HashSet<Diachi>(0);

	public Duong() {
	}

	public Duong(String tenduong) {
		this.tenduong = tenduong;
	}

	public Duong(String tenduong, Set<Diachi> diachis) {
		this.tenduong = tenduong;
		this.diachis = diachis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DUONGID", unique = true, nullable = false)
	public Integer getDuongid() {
		return this.duongid;
	}

	public void setDuongid(Integer duongid) {
		this.duongid = duongid;
	}

	@Column(name = "TENDUONG", nullable = false, length = 100)
	public String getTenduong() {
		return this.tenduong;
	}

	public void setTenduong(String tenduong) {
		this.tenduong = tenduong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "duong")
	public Set<Diachi> getDiachis() {
		return this.diachis;
	}

	public void setDiachis(Set<Diachi> diachis) {
		this.diachis = diachis;
	}

}
