package vn.com.nhatro.model;
// default package
// Generated Sep 1, 2014 7:11:03 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hinh generated by hbm2java
 */
@Entity
@Table(name = "hinh", catalog = "nhatro")
public class Hinh implements java.io.Serializable {

	private Integer hinhid;
	private Nhatro nhatro;
	private String duongdan;

	public Hinh() {
	}

	public Hinh(Nhatro nhatro, String duongdan) {
		this.nhatro = nhatro;
		this.duongdan = duongdan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "HINHID", unique = true, nullable = false)
	public Integer getHinhid() {
		return this.hinhid;
	}

	public void setHinhid(Integer hinhid) {
		this.hinhid = hinhid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NHATROID", nullable = false)
	public Nhatro getNhatro() {
		return this.nhatro;
	}

	public void setNhatro(Nhatro nhatro) {
		this.nhatro = nhatro;
	}

	@Column(name = "DUONGDAN", nullable = false, length = 200)
	public String getDuongdan() {
		return this.duongdan;
	}

	public void setDuongdan(String duongdan) {
		this.duongdan = duongdan;
	}

}
