package vn.com.nhatro.model;

// default package
// Generated Aug 30, 2014 10:27:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khac generated by hbm2java
 */
@Entity
@Table(name = "khac", catalog = "nhatro")
public class Khac implements java.io.Serializable {

	private Integer khacid;
	private String noidug;
	private Set<Diachi> diachis = new HashSet<Diachi>(0);

	public Khac() {
	}

	public Khac(String noidug) {
		this.noidug = noidug;
	}

	public Khac(String noidug, Set<Diachi> diachis) {
		this.noidug = noidug;
		this.diachis = diachis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "KHACID", unique = true, nullable = false)
	public Integer getKhacid() {
		return this.khacid;
	}

	public void setKhacid(Integer khacid) {
		this.khacid = khacid;
	}

	@Column(name = "NOIDUG", nullable = false, length = 100)
	public String getNoidug() {
		return this.noidug;
	}

	public void setNoidug(String noidug) {
		this.noidug = noidug;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khac")
	public Set<Diachi> getDiachis() {
		return this.diachis;
	}

	public void setDiachis(Set<Diachi> diachis) {
		this.diachis = diachis;
	}

}
