package vn.com.nhatro.model;
// default package
// Generated Sep 1, 2014 7:11:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loai generated by hbm2java
 */
@Entity
@Table(name = "loai", catalog = "nhatro")
public class Loai implements java.io.Serializable {

	private Integer loaiid;
	private String tenloai;
	private Set<Nhatro> nhatros = new HashSet<Nhatro>(0);

	public Loai() {
	}

	public Loai(String tenloai) {
		this.tenloai = tenloai;
	}

	public Loai(String tenloai, Set<Nhatro> nhatros) {
		this.tenloai = tenloai;
		this.nhatros = nhatros;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LOAIID", unique = true, nullable = false)
	public Integer getLoaiid() {
		return this.loaiid;
	}

	public void setLoaiid(Integer loaiid) {
		this.loaiid = loaiid;
	}

	@Column(name = "TENLOAI", nullable = false, length = 20)
	public String getTenloai() {
		return this.tenloai;
	}

	public void setTenloai(String tenloai) {
		this.tenloai = tenloai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loai")
	public Set<Nhatro> getNhatros() {
		return this.nhatros;
	}

	public void setNhatros(Set<Nhatro> nhatros) {
		this.nhatros = nhatros;
	}

}
