package vn.com.nhatro.model;

// default package
// Generated Aug 30, 2014 10:27:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistentlogin generated by hbm2java
 */
@Entity
@Table(name = "persistentlogin", catalog = "nhatro")
public class Persistentlogin implements java.io.Serializable {

	private Integer series;
	private String usernametemp;
	private String token;
	private Date lastUsed;

	public Persistentlogin() {
	}

	public Persistentlogin(String usernametemp, String token, Date lastUsed) {
		this.usernametemp = usernametemp;
		this.token = token;
		this.lastUsed = lastUsed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SERIES", unique = true, nullable = false)
	public Integer getSeries() {
		return this.series;
	}

	public void setSeries(Integer series) {
		this.series = series;
	}

	@Column(name = "USERNAMETEMP", nullable = false, length = 200)
	public String getUsernametemp() {
		return this.usernametemp;
	}

	public void setUsernametemp(String usernametemp) {
		this.usernametemp = usernametemp;
	}

	@Column(name = "TOKEN", nullable = false, length = 64)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_USED", nullable = false, length = 19)
	public Date getLastUsed() {
		return this.lastUsed;
	}

	public void setLastUsed(Date lastUsed) {
		this.lastUsed = lastUsed;
	}

}
