package vn.com.nhatro.model;
// default package
// Generated Sep 1, 2014 7:11:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "nhatro")
public class User implements java.io.Serializable {

	private String username;
	private String password;
	private String email;
	private Boolean enabled;
	private Set<Userrole> userroles = new HashSet<Userrole>(0);
	private Set<Nhatro> nhatros = new HashSet<Nhatro>(0);
	private Set<Thich> thiches = new HashSet<Thich>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);

	public User() {
	}

	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public User(String username, String password, String email,
			Boolean enabled, Set<Userrole> userroles, Set<Nhatro> nhatros,
			Set<Thich> thiches, Set<Comment> comments) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.enabled = enabled;
		this.userroles = userroles;
		this.nhatros = nhatros;
		this.thiches = thiches;
		this.comments = comments;
	}

	@Id
	@Column(name = "USERNAME", unique = true, nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", nullable = false, length = 10)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ENABLED")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Userrole> getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Set<Userrole> userroles) {
		this.userroles = userroles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Nhatro> getNhatros() {
		return this.nhatros;
	}

	public void setNhatros(Set<Nhatro> nhatros) {
		this.nhatros = nhatros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Thich> getThiches() {
		return this.thiches;
	}

	public void setThiches(Set<Thich> thiches) {
		this.thiches = thiches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
