package vn.com.nhatro.model;

// default package
// Generated Aug 30, 2014 10:27:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phuong generated by hbm2java
 */
@Entity
@Table(name = "phuong", catalog = "nhatro")
public class Phuong implements java.io.Serializable {

	private Integer phuongid;
	private String tenphuong;
	private Set<Diachi> diachis = new HashSet<Diachi>(0);

	public Phuong() {
	}

	public Phuong(String tenphuong) {
		this.tenphuong = tenphuong;
	}

	public Phuong(String tenphuong, Set<Diachi> diachis) {
		this.tenphuong = tenphuong;
		this.diachis = diachis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PHUONGID", unique = true, nullable = false)
	public Integer getPhuongid() {
		return this.phuongid;
	}

	public void setPhuongid(Integer phuongid) {
		this.phuongid = phuongid;
	}

	@Column(name = "TENPHUONG", nullable = false, length = 100)
	public String getTenphuong() {
		return this.tenphuong;
	}

	public void setTenphuong(String tenphuong) {
		this.tenphuong = tenphuong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phuong")
	public Set<Diachi> getDiachis() {
		return this.diachis;
	}

	public void setDiachis(Set<Diachi> diachis) {
		this.diachis = diachis;
	}

}
