package vn.com.nhatro.model;

// default package
// Generated Aug 30, 2014 10:27:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quan generated by hbm2java
 */
@Entity
@Table(name = "quan", catalog = "nhatro")
public class Quan implements java.io.Serializable {

	private Integer quanid;
	private String tenquan;
	private Set<Diachi> diachis = new HashSet<Diachi>(0);

	public Quan() {
	}

	public Quan(String tenquan) {
		this.tenquan = tenquan;
	}

	public Quan(String tenquan, Set<Diachi> diachis) {
		this.tenquan = tenquan;
		this.diachis = diachis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QUANID", unique = true, nullable = false)
	public Integer getQuanid() {
		return this.quanid;
	}

	public void setQuanid(Integer quanid) {
		this.quanid = quanid;
	}

	@Column(name = "TENQUAN", nullable = false, length = 100)
	public String getTenquan() {
		return this.tenquan;
	}

	public void setTenquan(String tenquan) {
		this.tenquan = tenquan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quan")
	public Set<Diachi> getDiachis() {
		return this.diachis;
	}

	public void setDiachis(Set<Diachi> diachis) {
		this.diachis = diachis;
	}

}
