package vn.com.nhatro.model;

// default package
// Generated Aug 30, 2014 10:27:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Toado generated by hbm2java
 */
@Entity
@Table(name = "toado", catalog = "nhatro")
public class Toado implements java.io.Serializable {

	private Integer toadoid;
	private float x;
	private float y;
	private Set<Nhatro> nhatros = new HashSet<Nhatro>(0);

	public Toado() {
	}

	public Toado(float x, float y) {
		this.x = x;
		this.y = y;
	}

	public Toado(float x, float y, Set<Nhatro> nhatros) {
		this.x = x;
		this.y = y;
		this.nhatros = nhatros;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TOADOID", unique = true, nullable = false)
	public Integer getToadoid() {
		return this.toadoid;
	}

	public void setToadoid(Integer toadoid) {
		this.toadoid = toadoid;
	}

	@Column(name = "X", nullable = false, precision = 12, scale = 0)
	public float getX() {
		return this.x;
	}

	public void setX(float x) {
		this.x = x;
	}

	@Column(name = "Y", nullable = false, precision = 12, scale = 0)
	public float getY() {
		return this.y;
	}

	public void setY(float y) {
		this.y = y;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toado")
	public Set<Nhatro> getNhatros() {
		return this.nhatros;
	}

	public void setNhatros(Set<Nhatro> nhatros) {
		this.nhatros = nhatros;
	}

}
